### ISSUE TITLE
[Court] Disputes should be one at a time, and historical dispute data should be kept around until resolution

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#372] opened 2021-11-19 11:30 UTC
The current implementation of the Court pallet needs to be improved in two respects:

- A market can only have one "court case" occurring at once. Currently the pallet allows for disputes to take place without any waiting time, overwriting the previous data immediately. A new court case can only be called after the conclusion of the prior court case.
- We need to keep historical data of court cases for a market, at least until that market resolves. This is so that we can properly reward / slash good and bad actors during the entire proceedings of cases. Once a market resolves, and the rewards and slashes have been divvied out, the items can be deleted from storage.

**Comment by Robiquet** [comment] 2021-12-10 10:43
A few other notes from my side:
- Votes can be changed, even after the end block has passed
- Jurors that have failed to vote still have the 'ok' status, I was expecting them to become 'tardy'
- Disputes can be created when there are no jurors
- When someone joins the court they are not added to existing cases despite being needed (not sure if this is by design)

**Comment by maltekliemann** [comment] 2022-06-19 11:23
I propose the following solution: The `dispute` method of `DisputeApi` may error with `DisputeInProgress` if a dispute has already been registered, but hasn't been handled by the dispute mechanism. For example:

- `Authorized::dispute` errors with `DisputeInProgress` if the market has been disputed but the authorized account hasn't responed yet
- `Court::dispute` errors with `DisputeInProgress` if the market has been disputed but the court case is not yet closed

This solution won't work with `SimpleDisputes`, but since that's getting removed anyways, we're fine.

**Comment by maltekliemann** [comment] 2022-08-03 13:24
Another problem uncovered in recent meetings: When using `authorized`, people can call `dispute` even after the authority has submitted a report.

I think the correct solution is to make appeals (i.e. second, third, etc. disputes) part of the `DisputeApi` and only have a single dispute in `prediction-markets`, which, if called, passes control for the decision of the market over to the dispute mechanism. This gives us more freedom in how we implement the `DisputeApi`. Then `authorized` be designed to now allow any appeals, but `court` can be.

**Comment by Chralt98** [comment] 2022-10-31 07:18
I added multiple issues to address ZIP-0 and ZIP-1 [here](https://github.com/zeitgeistpm/zeitgeist/issues?q=is%3Aissue+is%3Aopen+ZIP).

**Comment by Chralt98** [comment] 2023-10-18 10:12
Fixed by https://github.com/zeitgeistpm/zeitgeist/pull/976

**Closed by Chralt98** 2023-10-18 10:12 UTC
Labels: p:medium, t:bug, l:L
