### ISSUE TITLE
Add asset-registry benchmark and weight

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#1229] opened 2024-01-13 10:08 UTC
https://github.com/zeitgeistpm/zeitgeist/blob/d26dc8c85e0b942241379f15c0d3add4b456dda1/runtime/common/src/lib.rs#L567

**Comment by sea212** [comment] 2024-01-16 10:20
Duplicate of https://github.com/zeitgeistpm/zeitgeist/issues/884

**Closed by sea212** 2024-01-16 10:20 UTC
Labels: p:medium, l:S
