### ISSUE TITLE
Allow for market closure/settlement prior to market end date

### ISSUE THREAD

**Issue by davidhperry** [zeitgeistpm/zeitgeist#985] opened 2023-03-11 02:45 UTC
Scenario: Market creator makes a market along the lines of 'This event happens on or before August 1st. It's July 12th and the event happens, so we need to allow the market creator to close and settle the market then, rather than waiting out the clock and tying up people's time and ZTG.

**Comment by maltekliemann** [comment] 2023-03-13 13:17
Duplicate of #972 (sort of). There's been a discussion about this. I'm coming more from a user's perspective and think this is a very important feature. That being said, other voices are concerned about the amount of power this gives to the market creator (assuming they are responsible for closing the market).

The bottom line is: This requires some serious design decisions. Who's closing the market? What if they're wrong and the event hasn't happened yet?

**Comment by Chralt98** [comment] 2023-11-10 13:55
https://github.com/zeitgeistpm/zeitgeist/pull/1127

**Closed by Chralt98** 2023-11-10 13:55 UTC
