### ISSUE TITLE
[Tokens] Not able to query token balaces on `polkadot-ui` interface

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist#308] opened 2021-09-20 12:25 UTC
Querying token balances stopped working on https://polkadot.js.org/apps/ I get error in console
`DRR: Iteration tokens.accounts needs arguments to be at least one less than the full arguments, found [5Cogct4f5ThQZJBVywY2a5GKW8LU3hvwdm8dqjLRikzpshMt, [object Object]]`

![image](https://user-images.githubusercontent.com/551965/134001757-3b4419d2-8163-497f-951c-9341a0d2b9f3.png)

Code in the `proto` still works, but not on polkadot ui

i'm getting the same error on proto when I use `api.query.tokens.accounts.entries(address, { CategoricalOutcome: [0,0] })`but not with `query.tokens.accounts(address, { CategoricalOutcome: [0,0] } )`

**Comment by sea212** [comment] 2022-07-13 18:30
Closing this because I can't reproduce the error anymore. Please reopen if that is not the case.

**Closed by sea212** 2022-07-13 18:30 UTC
