### ISSUE TITLE
Add pallet-xcm benchmark and weights

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#1230] opened 2024-01-13 13:58 UTC
https://github.com/zeitgeistpm/zeitgeist/blob/a5f4b397ba09a95bb2037255dbec99ac6844e4e1/runtime/common/src/lib.rs#L533

We just use the standard test weights for xcm functions. We might want to benchmark our own weights for our reference machine.

**Comment by sea212** [comment] 2024-01-16 10:21
Duplicate of https://github.com/zeitgeistpm/zeitgeist/issues/1082

**Closed by sea212** 2024-01-16 10:21 UTC
Labels: p:medium, l:S
